module.exports = {
  projectRoutes: require('./projectRoutes'),
  updateRoutes: require('./updateRoutes'),
  getAllTheUsers: require('./userRoutes/getAllTheUsers'),
  infoRoutes: require('./infoRoutes'),
  userRoutes: require('./userRoutes'),
  authRoutes: require('./authRoutes'),
  CreateNewHeadDepartment: require('./CreateNewHeadDepartment'),
  deleteHeadDepartment: require('./deleteHeadDepartment'),
  projectRoutes: require('./projectRoutes'),
  deleteEmployee: require('./deleteEmployee/deleteEmployee'),
  meetingRoutes: require('./meetingRoutes'),
  filterMeetingsRoutes: require("./filterMeetings/filterMeetingsRoutes"),
  dashboardRoutes: require('./dashboardRoutes'),
  notificationRoutes: require('./notificationRoutes'),
};
